"""empty message

Revision ID: 9eac1e5fafb8
Revises: 
Create Date: 2020-10-27 23:19:54.175301

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9eac1e5fafb8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contactus',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('message', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('searchedsongsbucket',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('song_id', sa.String(length=50), nullable=True),
    sa.Column('download', sa.Boolean(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tutorials_tbl')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tutorials_tbl',
    sa.Column('tutorial_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('tutorial_title', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('tutorial_author', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('submission_date', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('tutorial_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('searchedsongsbucket')
    op.drop_table('contactus')
    # ### end Alembic commands ###
